service: bref-demo

provider:
  name: aws
  region: eu-west-1
  runtime: provided

plugins:
  - ./vendor/bref/bref

functions:
  bref_fpm:
    handler: public/index.php
    timeout: 28
    layers:
      - ${bref:layer.php-74-fpm}
    events:
      -   http: 'ANY /fpm'
    environment:
      # Symfony environment variables
      APP_ENV: prod
      APP_SECRET: 6b566e17cf0965eb4db2fef5f41bae18

  bref_fpm_new:
    handler: public/index.php
    timeout: 28
    layers:
      - 'arn:aws:lambda:eu-west-1:403367587399:layer:php-74-fpm:1'
    events:
      -   http: 'ANY /fpm-new'
    environment:
      # Symfony environment variables
      APP_ENV: prod
      APP_SECRET: 6b566e17cf0965eb4db2fef5f41bae18

  bref_function:
    handler: bin/lambda.php
    timeout: 28
    layers:
      - 'arn:aws:lambda:eu-west-1:403367587399:layer:php-74:1'
    events:
      -   http: 'ANY /func'
    environment:
      # Symfony environment variables
      APP_ENV: prod
      APP_SECRET: 6b566e17cf0965eb4db2fef5f41bae18
      BREF_LOOP_MAX: 1

  bref_keepalive:
    handler: bin/lambda.php
    timeout: 28
    layers:
      - 'arn:aws:lambda:eu-west-1:403367587399:layer:php-74:1'
    events:
      -   http: 'ANY /alive'
    environment:
      # Symfony environment variables
      APP_ENV: prod
      APP_SECRET: 6b566e17cf0965eb4db2fef5f41bae18
      BREF_LOOP_MAX: 500